language: go

matrix:
  include:
    - go: "1.13"
    
# Install all external dependencies, ensuring they are updated.
install:
- go get github.com/bwmarrin/discordgo
- go get github.com/koffeinsource/go-imgur
- go get github.com/koffeinsource/go-klogger
- go get github.com/thehowl/go-osuapi
- go get github.com/lib/pq
- go get github.com/op/go-logging
- go get github.com/gendonl/saucenao-go
- go get github.com/briandowns/openweathermap
- go get github.com/texttheater/golang-levenshtein/levenshtein

script:
- go test -v ./...